#!/usr/bin/env python 
# -*- coding: utf-8 -*-
# @Time    : 2024/10/29 15:06
# @Author  : 兵
# @email    : 1747193328@qq.com

import logging
import os.path
import shutil
import subprocess
from pathlib import Path

import numpy as np
from ase import Atoms
from ase.io import read as ase_read
from ase.io import write as ase_write

from NepTrain import utils, module_path
from NepTrain.exceptions import GPUMDExecutionError, GPUMDOutputError, FileOperationError

from ..select import select_structures, filter_by_bonds

from .io import RunInput

from ..utils import check_env

import zlib

logger = logging.getLogger(__name__)


def array_to_id(arr):
    """Compute CRC32 hash of array for unique identification.
    
    Args:
        arr: NumPy array
        
    Returns:
        int: CRC32 hash value
    """
    arr = np.ascontiguousarray(arr)  # Ensure memory contiguous
    return zlib.crc32(arr.tobytes())


@utils.iter_path_to_atoms(["*.vasp", "*.xyz"], show_progress=False)
def calculate_gpumd(atoms: Atoms, argparse) -> list[Atoms]:
    """
    Calculate GPUMD molecular dynamics trajectory for atoms.
    
    Args:
        atoms: ASE Atoms object
        argparse: Argument namespace with calculation parameters
        
    Returns:
        List of ASE Atoms objects from trajectory
        
    Raises:
        GPUMDExecutionError: If GPUMD calculation fails
        FileOperationError: If required files are missing
    """
    atoms_index = array_to_id(atoms.positions)
    new_atoms: list[Atoms] = []

    # Check required input files before processing
    run_in_path = Path(argparse.run_in_path)
    if not run_in_path.exists():
        raise FileOperationError(
            f"run.in file not found: {run_in_path}",
            path=str(run_in_path)
        )
    
    nep_txt_path = Path(argparse.nep_txt_path)
    if not nep_txt_path.exists():
        raise FileOperationError(
            f"nep.txt file not found: {nep_txt_path}",
            path=str(nep_txt_path)
        )

    for temperature in argparse.temperature:
        run = RunInput(str(nep_txt_path))
        
        if utils.is_file_empty(run_in_path):
            run_in_path = Path(module_path) / "core/gpumd/run.in"
        else:
            run_in_path = Path(argparse.run_in_path)
            
        run.read_run(str(run_in_path))
        run.set_time_temp(argparse.time, temperature)
        
        # Use Path for directory handling
        directory = Path(argparse.directory) / f"{atoms_index}-{atoms.symbols}@{temperature}k-{argparse.time}ps"
        directory.mkdir(parents=True, exist_ok=True)
        
        logger.info(f"GPUMD is running, temperature: {temperature}K. Time: {argparse.time}ps")

        try:
            run.calculate(atoms, str(directory))
            
            # Verify output files exist
            dump_path = directory / "dump.xyz"
            if not dump_path.exists():
                raise GPUMDOutputError(
                    f"dump.xyz not generated by GPUMD",
                    expected_file=str(dump_path)
                )
                
            thermo_path = directory / "thermo.out"
            if not thermo_path.exists():
                logger.warning(f"thermo.out not generated, may affect analysis: {thermo_path}")
            
            dump = ase_read(str(dump_path), ":", format="extxyz", do_not_split_by_at_sign=True)
            
            for i, atom in enumerate(dump):
                atom.info["Config_type"] = f"{atom.symbols}-epoch-{argparse.time}ps-{temperature}K-{i + 1}"

            new_atoms.extend(dump)

        except subprocess.CalledProcessError as e:
            raise GPUMDExecutionError(
                f"GPUMD calculation failed with return code {e.returncode}",
                return_code=e.returncode,
                error_file=str(directory / "gpumd.err")
            ) from e
        except FileNotFoundError as e:
            raise GPUMDExecutionError(
                f"GPUMD executable not found or failed to start",
                error_file=str(directory / "gpumd.err")
            ) from e

    return new_atoms


def run_gpumd(argparse):
    """
    Run GPUMD calculations for all structures.
    
    Args:
        argparse: Argument namespace with calculation parameters
        
    Raises:
        FileOperationError: If output directory cannot be created
    """
    check_env()
    
    # Use Path for output directory
    out_file_path = Path(argparse.out_file_path)
    out_dir = out_file_path.parent
    
    if out_dir and not out_dir.exists():
        try:
            out_dir.mkdir(parents=True, exist_ok=True)
        except OSError as e:
            raise FileOperationError(
                f"Failed to create output directory: {out_dir}",
                path=str(out_dir)
            ) from e
    
    result = calculate_gpumd(argparse.model_path, argparse)
    
    # Filter vacancies before writing
    if isinstance(result, list):
        result = [_filter_vacancies_for_export(atoms) for atoms in result]
    else:
        result = [_filter_vacancies_for_export(result)]
        
    ase_write(str(out_file_path), result, append=True, format="extxyz")
    
    utils.print_success("GPUMD calculation task completed!")


# Import here to avoid circular import
def _filter_vacancies_for_export(atoms):
    """Filter out vacancy atoms from structure.
    
    Args:
        atoms: ASE Atoms object
        
    Returns:
        Filtered ASE Atoms object
    """
    # Check if vacancy filtering is needed
    if hasattr(atoms, 'info') and 'vacancies' in atoms.info:
        indices_to_keep = [
            i for i, symbol in enumerate(atoms.get_chemical_symbols())
            if symbol != 'X'  # 'X' represents vacancy
        ]
        if indices_to_keep:
            return atoms[indices_to_keep]
    return atoms


if __name__ == '__main__':
    calculate_gpumd("./")
